// Generated by CoffeeScript 2.4.1
var appConfig = require('./app/config');
var theme = appConfig.site.theme

exports.config = {
  // http://brunch.io/docs/config
  plugins: {
    coffeelint: {
      pattern: /^app\/.*\.coffee$/,
      options: {
        indentation: {
          value: 2,
          level: 'error'
        },
        max_line_length: {
          value: 160
        }
      }
    },
    cleancss: {
      keepSpecialComments: 0,
      removeEmpty: true
    },
    sass: {
      mode: 'native',
      options: {
        includePaths: [
          'node_modules/bootstrap/scss/',
          `app/styles/_themes/${theme}`
        ],
        debug: 'debug',
        sourceMapEmbed: true,
      }
    },
    terser: {
      mangle: false
    },
    copycat: {
      icons: ['node_modules/bootstrap-icons/icons'],
      verbose: true,
      onlyChanged: true
    },
    cachebust: {
      manifest: 'public/cachebust-manifest.json'
    },
  },
  server: {
    hostname: "0.0.0.0",
    port: 3333
  },
  files: {
    javascripts: {
      joinTo: {
        'javascripts/app.js': /^app/,
        'javascripts/vendor.js': /^(?!app)/
      }
    },
    stylesheets: {
      joinTo: {
        'stylesheets/app.css': /^app/,
        'stylesheets/vendor.css': /^(?!app)/
      }
    }
  },
  sourceMaps: "absoluteUrl"
};
